export const LOAD_PHOTOS = "LOAD_PHOTOS";
export const LOAD_PHOTOS_SUCCESS = 'LOAD_PHOTOS_SUCCESS';
export const UPDATE_FILTER = 'UPDATE_FILTER';
export const LOAD_PHOTOS_ERROR = 'LOAD_PHOTOS_ERROR';
